name: 'Airplane Deploy'
description: 'Build and deploy task code to airplane.dev'
author: "support@airplane.dev"
branding:
  color: blue
  icon: cloud-lightning
inputs:
  api-key:
    required: true
    description: "Your Airplane API Key. You can create one here: app.airplane.dev"
  team-id:
    required: true
    description: Your Airplane Team ID.
  host:
    required: false
    description: Airplane API Host.
    default: api.airplane.dev
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
  env:
    AP_API_KEY: ${{ inputs.api-key }}
    AP_TEAM_ID: ${{ inputs.team-id }}
