name: 'Airplane Deploy'
description: 'Build and deploy task code to airplane.dev'
author: "support@airplane.dev"
branding:
  color: blue
  icon: cloud-lightning
inputs:
  api-key:
    required: true
    description: Your Airplane API Key.
  team-id:
    required: true
    description: Your Airplane Team ID.
  host:
    required: false
    description: Airplane API Host.
    default: api.airplane.dev
  task-directory:
    required: false
    description: Directory that contains airplane tasks.
    default: ./
runs:
  using: "composite"
  steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
      with:
        format: 'csv'
    - run: echo ${{ steps.files.outputs.all }} | tr ',' '\n' > .airplane_changed_files.txt
      shell: bash
    - uses: actions/checkout@v2
      with:
        repository: airplanedev/airplane-deploy
        ref: refs/tags/v1
        path: .github/.airplane_actions/
    - uses: ./.github/.airplane_actions/deploy
      with:
        api-key: ${{ inputs.api-key }}
        team-id: ${{ inputs.team-id }}
        host: ${{ inputs.host }}
        task-directory: ${{ inputs.task-directory }}
        changed-files: .airplane_changed_files.txt
    - run: rm .airplane_changed_files.txt && rm -rf ./.github/.airplane_actions
      shell: bash
