name: 'Airplane Deploy'
description: 'Build and deploy task code to airplane.dev'
author: "support@airplane.dev"
branding:
  color: blue
  icon: cloud-lightning
inputs:
  api-key:
    required: true
    description: Your Airplane API Key.
  team-id:
    required: true
    description: Your Airplane Team ID.
  host:
    required: false
    description: Airplane API Host.
    default: api.airplane.dev
  task-directory:
    required: false
    description: Directory that contains airplane tasks.
    default: ./
  repository:
    required: false
    description: Repository name with owner.
    default: ${{ github.repository }}
  user-name:
    required: false
    description: GitHub user who triggered the deploy.
    default: ${{ github.actor }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.host }}
    - ${{ inputs.task-directory }}
  env:
    AP_API_KEY: ${{ inputs.api-key }}
    AP_TEAM_ID: ${{ inputs.team-id }}
    AP_GIT_REPO: ${{ inputs.repository }}
    AP_GIT_USER: ${{ inputs.user-name }}
