name: "Airplane Deploy"
description: "Build and deploy task code to airplane.dev"
author: "support@airplane.dev"
branding:
  color: blue
  icon: cloud-lightning
inputs:
  api-key:
    required: true
    description: Your Airplane API Key.
  team-id:
    required: true
    description: Your Airplane Team ID.
  host:
    required: false
    description: Airplane API Host.
    default: api.airplane.dev
  env:
    required: false
    description: Airplane environment to deploy in.
    default: ""
  task-directory:
    required: false
    description: Directory that contains airplane tasks.
    default: ./
  repository:
    required: false
    description: Repository name with owner.
    default: ${{ github.repository }}
  user-name:
    required: false
    description: GitHub user who triggered the deploy.
    default: ${{ github.actor }}
runs:
  using: "composite"
  steps:
    # Checkout entire repo for the changed files step.
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Get all files changed from the last commit on the remote branch.
    - id: files
      uses: tj-actions/changed-files@v20
      with:
        separator: ","
        since_last_remote_commit: true
    # Write the CSV changed files into a newline separated file expected by the Airplane CLI.
    - run: echo ${{ steps.files.outputs.all_changed_files }} | tr ',' '\n' > .airplane_changed_files.txt
      shell: bash
    # Run the Airplane deploy action, forwarding all inputs plus the changed files.
    - uses: airplanedev/airplane-deploy/deploy@v1
      with:
        api-key: ${{ inputs.api-key }}
        team-id: ${{ inputs.team-id }}
        host: ${{ inputs.host }}
        env: ${{ inputs.env }}
        task-directory: ${{ inputs.task-directory }}
        repository: ${{ inputs.repository }}
        user-name: ${{ inputs.user-name }}
        changed-files: .airplane_changed_files.txt
    # Remove artifact created with this action.
    - run: rm .airplane_changed_files.txt
      shell: bash
