name: "Airplane Deploy"
description: "Build and deploy task code to airplane.dev"
author: "support@airplane.dev"
branding:
  color: blue
  icon: cloud-lightning
inputs:
  api-key:
    required: true
    description: Your Airplane API Key.
  team-id:
    required: true
    description: Your Airplane Team ID.
  host:
    required: false
    description: Airplane API Host.
    default: api.airplane.dev
  env:
    required: false
    description: Airplane environment to deploy in.
    default: ""
  task-directory:
    required: false
    description: Directory that contains airplane tasks.
    default: ./
  repository:
    required: false
    description: Repository name with owner.
    default: ${{ github.repository }}
  user-name:
    required: false
    description: GitHub user who triggered the deploy.
    default: ${{ github.actor }}
  changed-files:
    required: false
    description: A file containing newline-separate changed files. Only Airplane tasks that reference these files will be deployed.
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.host }}
    - ${{ inputs.task-directory }}
    - ${{ inputs.env }}
    - ${{ inputs.changed-files }}
  env:
    AP_API_KEY: ${{ inputs.api-key }}
    AP_TEAM_ID: ${{ inputs.team-id }}
    AP_GIT_REPO: ${{ inputs.repository }}
    AP_GIT_USER: ${{ inputs.user-name }}
    AP_SOURCE: githubAction
